import contextlib
import io
import json
import re
import sys
import openai
from openai import OpenAI
import streamlit as st
import sympy as sp

try:
    from hyperon import MeTTa
except ImportError:
    st.error(
        "The `hyperon` library is missing. Please run `pip install hyperon`.",
        icon="⚠️",
    )
    st.stop()

# ==========================================
# 1. Page Settings & Setup
# ==========================================
st.set_page_config(
    page_title="Global Banach Micro-AGI", page_icon="🧠", layout="wide"
)
st.title("🧠 Global Banach Space Micro-AGI")
st.write(
    "Collaborative Neuro-Symbolic Cognitive Loop Engine."
)

if "OPENROUTER_API_KEY" not in st.secrets:
    st.error("Missing `OPENROUTER_API_KEY` in Streamlit Secrets!", icon="🚨")
    st.stop()


# ==========================================
# 2. Centralized Global MeTTa Engine
# ==========================================
@st.cache_resource
def get_global_metta_engine():
    metta = MeTTa()
    metta.run("""
        ;; Base Structural Ontology
        (: VectorSpace Type)
        (: BanachSpace Type)
        (: Complete Property)
        (: Normed Property)

        ;; Fundamental Rules
        (= (is-banach $space) (and (has-property $space Normed) (has-property $space Complete)))
        
        ;; Peer-Reviewed Core Truths
        (: L2 VectorSpace)
        (has-property L2 Normed)
        (has-property L2 Complete)
    """)
    return metta


global_metta = get_global_metta_engine()
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=st.secrets["OPENROUTER_API_KEY"],
)


# Helper tools pointing to the global instance
def run_global_metta(query_string):
    try:
        res = global_metta.run(query_string)
        return str(res)
    except Exception as e:
        return f"MeTTa Error: {str(e)}"


def run_local_sympy(code_string):
    output_buffer = io.StringIO()
    local_env = {"sp": sp, "sympy": sp}
    try:
        with contextlib.redirect_stdout(output_buffer):
            exec(code_string, {}, local_env)
        return output_buffer.getvalue()
    except Exception as e:
        return f"SymPy Error: {str(e)}"


# ==========================================
# 3. Text Post-Processing (Robust Math Render)
# ==========================================
def clean_and_format_latex(text):
    """Normalizes conflicting LLM LaTeX and Markdown configurations

    for flawless, presentation-grade math rendering in Streamlit.
    """
    if not text:
        return ""

    # Convert standard block delimiters
    text = text.replace(r"\[", "\n$$\n").replace(r"\]", "\n$$\n")
    text = text.replace(r"\(", " $ ").replace(r"\)", " $ ")

    # Standardize LaTeX environments often generated by technical reasoners
    text = re.sub(r"\\begin\{equation\*?\}(.*?)\\end\{equation\*?\}", r"\n$$\1$$\n", text, flags=re.DOTALL)
    text = re.sub(r"\\begin\{align\*?\}(.*?)\\end\{align\*?\}", r"\n$$\1$$\n", text, flags=re.DOTALL)

    # Protect double backslashes in alignment arrays from python string escaping
    text = text.replace(r"\\", r"\\\\")

    # Clean double spacing or artifact boundaries around inline markers
    text = text.replace("$$ $$", "$$")
    return text


# ==========================================
# 4. Chat Logic & Prompts
# ==========================================
MODEL_TARGET = "openrouter/free"

AGI_SYSTEM_PROMPT = (
    "You are an autonomous Micro-AGI Agent executing inside a global Neuro-Symbolic cognitive loop.\n"
    "Your specialization is Banach Space Theory and Functional Analysis.\n\n"
    "CRITICAL STRUCTURAL RULE:\n"
    "You must think step-by-step. To execute logic check or mathematical calculation, output a single JSON block.\n"
    "Do NOT output content or text surrounding the JSON when calling tools.\n\n"
    "COMMAND STRUCTURE:\n"
    "To evaluate logic, output a JSON block:\n"
    '{\n  "action": "tool_call",\n  "tool": "metta_eval",\n  "input": "!(is-banach L2)"\n}\n\n'
    "To commit a verified truth to global mind, output:\n"
    '{\n  "action": "tool_call",\n  "tool": "metta_publish",\n  "input": "(has-property YourNewSpace Complete)"\n}\n\n'
    "To deliver your final verified answer with rich mathematical proofs, output:\n"
    '{\n  "action": "final_answer",\n  "content": "Your complete math proof string using standard LaTeX."\n}'
)

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

# ==========================================
# 5. Interface Layout
# ==========================================
col_main, col_global_vault = st.columns([2, 1])

with col_main:
    st.subheader("🤖 Collaborative Thought Loop")

    for msg in st.session_state.chat_history:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    if user_input := st.chat_input("Enter research hypothesis..."):
        with st.chat_message("user"):
            st.markdown(user_input)
        st.session_state.chat_history.append(
            {"role": "user", "content": user_input}
        )

        with st.chat_message("assistant"):
            thought_container = st.status(
                "🧠 Consultation with Global Knowledge Base...", expanded=True
            )
            loop_messages = [
                {"role": "system", "content": AGI_SYSTEM_PROMPT},
                {"role": "user", "content": user_input},
            ]

            max_cycles = 5
            cycle = 0
            final_output = ""

            while cycle < max_cycles:
                cycle += 1
                raw_step = ""

                try:
                    response = client.chat.completions.create(
                        model=MODEL_TARGET, 
                        messages=loop_messages,
                        temperature=0.1
                    )
                    
                    # FIX: Defensive check to completely protect against NoneType output streams
                    message_content = response.choices[0].message.content
                    if message_content is not None:
                        raw_step = message_content.strip()
                    else:
                        raw_step = ""

                    # Clean potential markdown wrapping around JSON strings
                    json_clean = re.sub(r"^```json|```$", "", raw_step, flags=re.IGNORECASE).strip()
                    command = json.loads(json_clean)
                except Exception as e:
                    if not raw_step:
                        # Fallback step if the routing layer drops connectivity entirely
                        command = {
                            "action": "final_answer",
                            "content": "The routing engine encountered an empty stream frame response. Please submit your hypothesis query again to re-engage the loop.",
                        }
                    else:
                        # Fallback if text is outputted directly without explicit JSON wrapper logic
                        command = {"action": "final_answer", "content": raw_step}

                if command.get("action") == "tool_call":
                    tool_name = command.get("tool")
                    tool_input = command.get("input")

                    if tool_name == "metta_eval":
                        observation = run_global_metta(tool_input)
                    elif tool_name == "metta_publish":
                        observation = run_global_metta(tool_input)
                        observation = "COMMITTED TO GLOBAL KNOWLEDGE ACCESSIBLE BY ALL USERS."
                    elif tool_name == "sympy_calc":
                        observation = run_local_sympy(tool_input)
                    else:
                        observation = "Error: Invalid tool connection choice."

                    loop_messages.append({"role": "assistant", "content": raw_step})
                    loop_messages.append(
                        {
                            "role": "system",
                            "content": f"Observation: {observation}",
                        }
                    )

                elif command.get("action") == "final_answer":
                    final_output = command.get("content")
                    break

            # Clean and normalize mathematical markdown blocks
            final_output = clean_and_format_latex(final_output)

            thought_container.update(
                label="✅ Output Compiled!", state="complete", expanded=False
            )
            
            if final_output:
                st.markdown(final_output)
                st.session_state.chat_history.append(
                    {"role": "assistant", "content": final_output}
                )

with col_global_vault:
    st.subheader("🏛️ Shared Peer-Reviewed Vault")
    st.write(
        "Logical assertions currently verified common to **all** global users."
    )

    if st.button("Query Global Knowledge Graph"):
        vault_snapshot = run_global_metta(
            "!(match &self (has-property $space $prop) ($space $prop))"
        )
        st.code(vault_snapshot, language="lisp")
    else:
        st.caption("Click to pull down live peer-reviewed axioms from the cloud.")
